app:
  project: deploy-flask
  tier: flask-application

image:
  repository: hopar/flask
  tag: latest

deployments: 
  containerName: flask-app
  containerPort: 4000
  imagePullPolicy: Always
  replicas: 1

service:
  type: LoadBalancer
  port: 4000         
  targetPort: 4000
