name: Build and publish a Docker image
on: [push]

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    #env:
    #  IMG_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build-push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: hopar/flask
            tags: 0.1.1
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}        
      
      
      #- name: Deploy
      #  run: |
      #        echo "${{ secrets.KUBE_CONFIG_FILE }}" > cfg.yaml
      #        kubectl --kubeconfig=cfg.yaml get nodes
      #        helm repo add deploy-flask https://nimramubashir.github.io/deploy-flask/  --kubeconfig cfg.yaml
      #        helm install flask3 deploy-flask/deploy-flask --version 0.1.0  -f infra/testing-values.yaml --kubeconfig cfg.yaml
              
      
      # helm install my-deploy-flask deploy-flask/deploy-flask --version 0.1.0  -f infra/testing-values.yaml --kubeconfig cfg.yaml
      #- name: Deploy
      #  run: |
      #        export DIGITALOCEAN_ACCESS_TOKEN=${{ secrets.DOCTL_TOKEN }}    
      #        echo "vars >$DIGITALOCEAN_ACCESS_TOKEN<"
      #        cd ~
      #        wget https://github.com/digitalocean/doctl/releases/download/v1.94.0/doctl-1.94.0-linux-amd64.tar.gz
      #        tar xf ~/doctl-1.94.0-linux-amd64.tar.gz
      #        sudo mv ~/doctl /usr/local/bin
      #        cd -
      #        doctl auth init --context github --access-token $DIGITALOCEAN_ACCESS_TOKEN
              

        #run: |
        #      helm repo add deploy-flask https://nimramubashir.github.io/deploy-flask/
        #      helm install my-deploy-flask deploy-flask/deploy-flask --version 0.1.0  -f infra/testing-values.yaml

       
