name: Build and publish a Docker image
on: [push]

jobs:
  build:
    name: Build & push docker image
    runs-on: ubuntu-latest
    #env:
    #  IMG_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build-push
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: hopar/flask
            tags: latest
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}        
      
      - name: Deploy
        run: |
              helm repo add deploy-flask https://nimramubashir.github.io/deploy-flask/
              helm install my-deploy-flask deploy-flask/deploy-flask --version 0.1.0  -f infra/testing-values.yaml
       
       
